### ISSUE TITLE
Usability enhacement: backup the user template before generating the slides

### ISSUE THREAD

**Issue by ferreiro** [k0kubun/md2key#41]
This library uses the same `template.key` for generating the presentation. So we are not longer available to reuse the template.key for other projects.

One idea could be:
1. Make a copy of the `template.key` called `final_presensation.key`
2. Then, runs the md2key script on `final_presensation.key` to generate the presentation.

The main advantage of this feature request is that we can reuse one template for multiple projects.

Also, one related idea for this library is let the user specify the name of the output file and the name of the template. A  syntax like this could help:

```
Bash
$ md2key test.md -t template.key -o final_presentation.key
```
Where -t -> template and -o -> output file

What do you think? Does it make sense?

**Comment by k0kubun** [comment]
There's no need to reuse template.key because "Keymote theme" (including master slides information) can be saved separately and it's the only part that can be reused for other projects.

And if you mean the order of combination of first slide's master slide and second slide's master slide, you should use .md2key for the purpose https://github.com/k0kubun/md2key/pull/32. It's more flexible to remember a specific master slide.
